framework:
    workflows:
        box_making:
            type: 'workflow' # or 'state_machine'
            marking_store:
                type: 'single_state' # or 'single_state'
                arguments:
                    - 'currentPlace'
            supports:
                - App\Entity\Box
                - App\Controller\Box\BoxRequest
            initial_place: empty
            places:
                - empty
                - desc_incomplete
                - desc_complete
                - products_incomplete
                - products_complete
                - validation_box
                - ok_box
            transitions:
                adding_budget:
                    from: empty
                    to: desc_incomplete
                adding_desc:
                    from: desc_incomplete
                    to: desc_complete
                desc_ok_from_empty:
                    from: empty
                    to: desc_complete
                adding_products:
                    from: desc_complete
                    to:   products_incomplete
                products_added:
                    from: products_incomplete
                    to: products_complete
                validation:
                    from: products_complete
                    to:   validation_box
                ok:
                    from: validation_box
                    to:   ok_box
                rejected:
                    from: validation_box
                    to:   products_incomplete