framework:
    workflows:
        box_making:
            type: 'workflow' # or 'state_machine'
            marking_store:
                type: 'single_state' # or 'single_state'
                arguments:
                    - 'currentPlace'
            supports:
                - App\Entity\Box
                - App\Controller\Box\BoxRequest
            initial_place: edition
            places:
                - edition
                - box_complete
                - validate
                - production
                - sent
            transitions:
                datas_added:
                    from: edition
                    to: box_complete
                products_validation:
                    from: box_complete
                    to: validate
                box_production:
                    from: validate
                    to: production
                box_sent:
                    from: production
                    to: sent
                products_missing:
                    from: box_complete
                    to: edition