#index:
#    path: /
#    controller: App\Controller\IndexController::index

accueil:
    path: /accueil
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    defaults:
        route: index
        permanent: true
